name = "remix-app-cloudflare"
compatibility_date = "2024-04-08"

[vars]
CLOUDFLARE_TURNSTILE_SECRET = "1x0000000000000000000000000000000AA"
CLOUDFLARE_TURNSTILE_SITEKEY = "1x00000000000000000000BB"
POSTMARK_API_TOKEN = "string"
POSTMARK_DEFAULT_FROM = "string"

[[d1_databases]]
database_id = "<db id>"
binding = "DB"
database_name = "DB"