name = "remix-app-cloudflare"
compatibility_date = "2024-04-08"

[vars]
POSTMARK_API_TOKEN = "string"
POSTMARK_DEFAULT_FROM = "string"

[[d1_databases]]
database_id = "<db id>"
binding = "DB"
database_name = "DB"